oro_theme_migration:
    datagrids_to_migrate:
        - base-frontend-payment-profiles-grid
        - frontend-creditcard-payment-profiles-grid
        - frontend-echeck-payment-profiles-grid
        - frontend-customer-user-shopping-lists-grid
        - frontend-customer-user-shopping-list-select-grid
        - frontend-customer-customer-user-grid
        - frontend-customer-user-savedsearch-list-grid
        - frontend-catalog-allproducts-grid
        - frontend-checkouts-grid
        - frontend-checkout-line-items-grid
        - frontend-single-page-checkout-line-items-grid
        - base-orders-grid
        - frontend-orders-grid
        - base-order-line-items-grid
        - order-line-items-grid-frontend
        - products-select-grid-frontend
        - frontend-product-search-grid
        - frontend-requests-grid
        - frontend-quotes-grid
        - frontend-customer-user-shopping-lists-base-grid
        - frontend-customer-user-shopping-list-grid
        - frontend-customer-user-shopping-list-assign-grid
        - frontend-customer-user-shopping-list-edit-grid
        - frontend-product-kit-in-shopping-lists-grid
        - frontend-menu-global-grid
        - frontend-menu-by-scope-grid
        - role-permission-grid
        - frontend-customer-user-role-permission-grid
        - frontend-customer-customer-user-roles-grid
        - frontend-customer-customer-users-grid-basic
        - frontend-customer-customer-users-grid-view
        - frontend-customer-customer-users-grid-update
        - frontend-customer-address-grid-base
        - frontend-customer-customer-address-grid
        - frontend-customer-customer-user-address-grid
        - order-products-previously-purchased-grid
        - basic-customer-customer-user-roles-grid
        - customer-customer-user-grid-base
        - customer-customer-user-grid-no-filter-base
        - oauth-client-frontend-grid
